[build]
builder = "nixpacks"
buildCommand = "bun install && bun run build"
watchPatterns = ["src/**/*", "server.js", "package.json"]

[deploy]
startCommand = "bun run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
numReplicas = 1

[deploy.envs]
BUN_VERSION = "1.0.0"
PORT = "3000"
NODE_ENV = "production"
NIXPACKS_BUN_VERSION = "1.0.0" 