services:
  - type: web
    name: blob-wars
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true 